# Default PCAP file to use if one isn't specified
PCAP ?= 4SICS-GeekLounge-151022.pcap

.PHONY: help up build down run zeek clean shell-python shell-zeek

# Default target when you just run 'make'
help:
	@echo "ICS Dev Environment Commands:"
	@echo "  make build      - Build the images and start the containers in the background"
	@echo "  make up         - Start the containers (no build)"
	@echo "  make down       - Stop and remove the containers"
	@echo "  make zeek       - Run Zeek against the default PCAP (or pass PCAP=name.pcap)"
	@echo "  make run        - Execute main.py inside the running Python container"
	@echo "  make clean      - Delete the generated JSON logs to start fresh"
	@echo "  make shell-py   - Open a bash shell inside the Python container"
	@echo "  make shell-zeek - Open a bash shell inside the Zeek container"

build:
	docker-compose up -d --build

up:
	docker-compose up -d

down:
	docker-compose down

# Runs Zeek against the PCAP. 
# Usage: 'make zeek' OR 'make zeek PCAP=my_custom_capture.pcap'
zeek:
	@echo "Running Zeek against /pcaps/$(PCAP)..."
	docker-compose exec zeek bash -c "cd /opt/zeek/logs/current && rm -f *.log && zeek -C -r /pcaps/$(PCAP) local packages"

# List logs generated by zeek
list-logs:
	docker-compose exec zeek ls -la /opt/zeek/logs/current

# Instantly runs your locally modified Python script inside the container
run:
	@echo "Executing Python Engine..."
	docker-compose exec python-engine python main.py

# Cleans up the dev_data folder so Filebeat starts with a blank slate
clean:
	@echo "Cleaning up generated logs..."
	rm -f dev_data/*.ndjson
	@echo "Logs cleared."

# Handy shortcuts for debugging
shell-py:
	docker-compose exec python-engine /bin/bash

shell-zeek:
	docker-compose exec zeek /bin/bash